### ISSUE TITLE
the demo in readme.md not works

### ISSUE THREAD

**Issue by keshidong** [Mayness/koa-proxy-middleware#2]
[the demo ](https://github.com/Mayness/koa-proxy-middleware#usage) not works, it can't transfer request from `http://localhost: 3000/` to `http://localhost:3333/`.
I built the service for `http://localhost:3333/`,  the service can get data normally when access the service directly.
but  via this demo that can't transfer request from the service  of `http://localhost: 3000/` to the service of `http://localhost:3333/`, it return `not found` when access `http://localhost: 3000/`.

**Comment by keshidong** [comment]
maybe need set `ctx.respond = false` at line 17 in file `lib/proxy.js`

**Comment by Mayness** [comment]
I checked and found nothing wrong,maybe you missing `proxies.context`
