### ISSUE TITLE
你好 此处正则似乎有问题

### ISSUE THREAD

**Issue by Estelle00** [Mayness/koa-proxy-middleware#5]
https://github.com/Mayness/koa-proxy-middleware/blob/cb808e9d2daad8d7e9c7f9c36aa1f6f03ac121fe/lib/proxy.js#L18
```js
const context = "api";
let reg = new RegExp('^' + context + '(/|/\\w+)?$')
reg.test("/api")  // false
reg.test("/api/12/3") // false
// update 
reg =  new RegExp('^' + context + '(/|/\\w+)*')
reg.test("/api")  // true
reg.test("/api/12/3") // true
```

**Comment by Estelle00** [comment]
@Mayness

**Comment by Mayness** [comment]
你好，这边在进入`nginx`方法之前加入`'/'`字段
https://github.com/Mayness/koa-proxy-middleware/blob/cb808e9d2daad8d7e9c7f9c36aa1f6f03ac121fe/lib/proxy.js#L51
所以在上面的context应该为
```
const context = "/api";
```
并且同时也需要是精准匹配，例如不能匹配`/api123`之类的

**Comment by Estelle00** [comment]
您好，此次是我debug进入的调试截图
当前值传入是 输出为false
![image](https://user-images.githubusercontent.com/5432828/70882533-0ba03800-200b-11ea-812b-733a7a8b6f61.png)

**Comment by Estelle00** [comment]
当出现多级时 比如 /api/12/123 输出内容为false
我那个正则确实有点问题
这样应该就对了
```js
new RegExp('^' + context + '(/|/\\w+)*$')
```

**Comment by Mayness** [comment]
对的，是我疏忽了，非常感谢！

**Comment by Mayness** [comment]
@Estelle00 版本已经更新到2.0.1，如果有问题的话请与我联系，没有了的话我就关闭了😁

**Comment by Estelle00** [comment]
应该没啥问题，淘宝的npm镜像不更新 -_-||

**Comment by Mayness** [comment]
是的，今天可能比较慢。。。

**Comment by Mayness** [comment]
@Estelle00 你好，我刚刚确认了一下，是之前的npm token失效了，现在重新改了一下，最新版本为`2.0.2`，麻烦再次确认一下

**Comment by Estelle00** [comment]
https://www.npmjs.com/package/koa-proxy-middleware 似乎还是没有

**Comment by Mayness** [comment]
你再刷新一下呢，从你打开的页面我看到的已经是`2.0.2`了

**Comment by Estelle00** [comment]
好了

**Comment by Mayness** [comment]
好的😁
